config/routes.rb
Rails.application.routes.draw do
  # get "hexfield/index" # don't want/need
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # hexfield
  resources :projects, except: [:edit]
  get "edit" => "hexfield#edit"

  # files
  post "api/get-project" => "hexfield#get_project"
  post "api/get-code-files" => "hexfield#get_code_files"
  post "api/get-media-files" => "hexfield#get_media_files"
  post "api/upload-code-files" => "hexfield#upload_code_file"
  post "api/upload-media-files" => "hexfield#upload_media_file"
  post "api/get-code-file" => "hexfield#private_get_code_file"
  post "api/get-media-file" => "hexfield#private_get_media_file"

  get "web/:user/:project/:file" => "hexfield#public_get_code_file"
  get "web/:user/:project/media/:file" => "hexfield#public_get_media_file"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "hexfield#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Hexfield" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= yield :head %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>